name: Rust CI 

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    
env:
  CARGO_TEAM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: cargo build --verbose --release

